Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Can contain only ASCII characters.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
        - AttributeName: sort
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
        - AttributeName: sort
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: albert_text_cat
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e888c8b1-7fe8-4b05-9835-f5b15d7db843
  Server:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-07d0cf3af28718ef8
      InstanceType: t2.micro
      IamInstanceProfile:
        Ref: InstanceProfile
      SecurityGroups:
        - Ref: WebServerSecurityGroup
      KeyName:
        Ref: KeyName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y
          sudo apt install awscli -y
          sudo apt install python3-pip -y
          sudo apt install redis-server -y
          sudo systemctl restart redis.service
          sudo apt install python3-venv -y
          cd /home
          sudo mkdir alb
          cd alb
          git clone https://github.com/ttotev/albert.git
          cd albert
          sudo python3 -m venv .env
          source .env/bin/activate
          sudo .env/bin/pip install -r requirements.txt
          cd app
          sudo nohup ../.env/bin/celery worker -A text_cat_server.celery --loglevel=info &
          sudo nohup ../.env/bin/python3 text_cat_server.py &
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d342abd1-32ef-4d2c-8985-828c3537ec6f
    DependsOn:
      - DynamoDBTable
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
        GroupDescription: Enable HTTP access via port 5000
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 5000
            ToPort: 5000
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 
                Ref: SSHLocation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 081f1ae6-621e-4981-9dff-46addc96d555
  IAMRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  "ec2.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies: 
          -
            PolicyName: "root"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action: "dynamodb:*"
                  Resource: "*"
        RoleName: EC2toDynamoDBRole
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "IAMRole"
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'Server'
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [Server, AvailabilityZone]
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [Server, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [Server, PublicIp]
Metadata:
  'AWS::CloudFormation::Designer':
    e888c8b1-7fe8-4b05-9835-f5b15d7db843:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    d342abd1-32ef-4d2c-8985-828c3537ec6f:
      size:
        width: 60
        height: 60
      position:
        x: -50
        'y': 110
      z: 0
      dependson:
        - e888c8b1-7fe8-4b05-9835-f5b15d7db843
    081f1ae6-621e-4981-9dff-46addc96d555:
      size:
        width: 60
        height: 60
      position:
        x: 165.33333333333334
        'y': 114.5
      z: 0
